data = [
  {"name" : "Cristiano Ronaldo", "follower_count" : 985.1, "description" : "Footballer", "country" : "Portugal"},
  {"name" : "Selena Gomez", "follower_count" : 689, "description" : "Musician and actress", "country" : "United States"},
  {"name" : "Justin Bieber", "follower_count" : 596.2, "description" : "Musician", "country" : "Canada"},
  {"name" : "Taylor Swift", "follower_count" : 552, "description" : "Musician", "country" : "United States"},
  {"name" : "Ariana Grande", "follower_count" : 508.3, "description" : "Musician and actress", "country" : "United States"},
  {"name" : "Kylie Jenner", "follower_count" : 508.56, "description" : "Reality TV personality and businesswoman", "country" : "United States"},
  {"name" : "Dwayne Johnson", "follower_count" : 495.85, "description" : "Actor and professional wrestler", "country" : "United States"},
  {"name" : "Kim Kardashian", "follower_count" : 450.96, "description" : "Reality TV personality and businesswoman", "country" : "United States"},
  {"name" : "Lionel Messi", "follower_count" : 502.31, "description" : "Footballer", "country" : "Argentina"},
  {"name" : "MrBeast", "follower_count" : 423.7, "description" : "YouTuber", "country" : "United States"},
  {"name" : "Katy Perry", "follower_count" : 365.6, "description" : "Musician", "country" : "United States"},
  {"name" : "Beyoncé", "follower_count" : 367.83, "description" : "Musician", "country" : "United States"},
  {"name" : "National Geographic", "follower_count" : 347.6, "description" : "Magazine", "country" : "United States"},
  {"name" : "Jennifer Lopez", "follower_count" : 333.7, "description" : "Musician and actress", "country" : "United States"},
  {"name" : "Kendall Jenner", "follower_count" : 331.9, "description" : "Reality TV personality and Model", "country" : "United States"},
  {"name" : "Nike", "follower_count" : 330, "description" : "Sportswear multinational", "country" : "United States"},
  {"name" : "Virat Kohli", "follower_count" : 323.6, "description" : "Cricketer", "country" : "India"},
  {"name" : "Neymar", "follower_count" : 315.9, "description" : "Footballer", "country" : "Brazil"},
  {"name" : "Nicki Minaj", "follower_count" : 306, "description" : "Musician", "country" : "Trinidad and Tobago"},
  {"name" : "World Health Organization", "follower_count" : 303.7, "description" : "Health Organization", "country" : "Global"},
  {"name" : "Rihanna", "follower_count" : 303.6, "description" : "Musician and businesswoman", "country" : "Barbados"},
  {"name" : "Miley Cyrus", "follower_count" : 302.4, "description" : "Musician and actress", "country" : "United States"},
  {"name" : "Kourtney Kardashian", "follower_count" : 273.2, "description" : "Reality TV personality", "country" : "United States"},
  {"name" : "Ellen DeGeneres", "follower_count" : 265.5, "description" : "Comedian", "country" : "United States"},
  {"name" : "T-Series", "follower_count" : 263.9, "description" : "YouTube channel", "country" : "India"},
  {"name" : "Kevin Hart", "follower_count" : 261.7, "description" : "Comedian and actor", "country" : "United States"},
  {"name" : "BTS_official", "follower_count" : 257.9, "description" : "Music band", "country" : "South Korea"},
  {"name" : "Real Madrid C.F.", "follower_count" : 250.3, "description" : "Football club", "country" : "Spain"},
  {"name" : "Cardi B", "follower_count" : 246.6, "description" : "Musician", "country" : "United States"},
  {"name" : "Beyoncé", "follower_count" : 314, "description" : "Musician", "country" : "United States"},
  {"name" : "Billie Eilish", "follower_count" : 200.5, "description" : "Musician", "country" : "United States"},
  {"name" : "Zendaya", "follower_count" : 185, "description" : "Actress and musician", "country" : "United States"},
  {"name" : "Shakira", "follower_count" : 224.5, "description" : "Musician", "country" : "Colombia"},
  {"name" : "Drake", "follower_count" : 305, "description" : "Musician", "country" : "Canada"},
  {"name" : "Elon Musk", "follower_count" : 253.4, "description" : "CEO, Twitter/X", "country" : "United States"},
  {"name" : "Will Smith", "follower_count" : 246.1, "description" : "Actor", "country" : "United States"},
  {"name" : "Khloé Kardashian", "follower_count" : 340.52, "description" : "Reality TV personality", "country" : "United States"},
  {"name" : "Mr Bean", "follower_count" : 215.7, "description" : "Character", "country" : "United Kingdom"},
  {"name" : "Barack Obama", "follower_count" : 131.9, "description" : "Former US President", "country" : "United States"}
]